# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.1-browsers`
      - image: circleci/python:3.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      - run:
          name: Install dependencies
          command: |
            python3 --version
            python3 -m pip install --user --upgrade pip
            python3 -m pip install --user pipenv
            python3 -m pipenv install --dev
            python3 -m pipenv run python manage.py collectstatic

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      # run tests!
      - run:
          name: run tests
          command: |
            python3 -m pipenv run test

      - store_artifacts:
          path: test-reports
          destination: test-reports
